[package]
name = "protein-translate"
version = "0.1.2"
authors = ["dweb0"]
documentation = "https://docs.rs/protein-translate/"
description = "Translate nucleotide sequence to protein."
homepage = "https://github.com/dweb0/protein-translate"
repository = "https://github.com/dweb0/protein-translate"
readme = "README.md"
keywords = ["bioinformatics", "translate", "dna", "rna", "protein"]
categories = ["algorithms", "science"]
license = "MIT/Apache-2.0"
edition = "2018"
exclude = ["/.travis.yml", "/benches/*", "/tests/*"]

[badges]
travis-ci = { repository = "dweb0/protein-translate" }

[features]
parallel = ["rayon"]

[dependencies]
rayon = { version = "1.1.0", optional = true }

[dev-dependencies]
criterion = "0.2.11"
lazy_static = "1.3.0"
phf = { version = "0.7.24", features = ["macros"] }
csv = "1.1"
fnv = "1.0.3"

[[bench]]
name = "bench"
harness = false
